# Site settings
title: Tamas Nagy
tagline: Bioinformatics graduate student at UCSF. Interested in systems biology, image analysis, math, mountains, etc
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl"
  Bioinformatics graduate student at UCSF. Interested in systems biology, image analysis, math, mountains, photography, and more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tamasnagy.com" # the base hostname & protocol for your site
twitter_username: tlngy
github_user: tlnagy
github_repo: tnsite

# Build settings
markdown: Pandoc
pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - bibliography: bibliography.bib
exclude:
  - build.sh
  - cv_template.tex
  - README.md
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:title/

# Gems
plugins:
  - jekyll-pandoc
  - jekyll-gallery-generator
  - jekyll-avatar

gallery:
  dir: photos
  title: "photos"
  title_prefix: ""
  sort_field: "datetime"
  sort_photos: "title"
  thumbnail_size:
    x: 400
    y: 400
